feat: update quilt to 0.68-1

diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -6,19 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
-setup_colors
-
 usage()
 {
 	printf $"Usage: quilt diff [-p n|-p ab] [-u|-U num|-c|-C num] [--combine patch|-z] [-R] [-P patch] [--snapshot] [--diff=utility] [--no-timestamps] [--no-index] [--sort] [--color[=always|auto|never]] [file ...]\n"
@@ -113,9 +100,7 @@ do_diff()
 		[ -s "$new_file" ] || new_file=/dev/null
 		if ! diff -q "$old_file" "$new_file" >/dev/null
 		then
-			export LANG=$ORIGINAL_LANG
-			$opt_diff "$old_file" "$new_file"
-			export LANG=POSIX
+			LANG=$ORIGINAL_LANG $opt_diff "$old_file" "$new_file"
 			true
 		fi
 	else
@@ -134,7 +119,7 @@ die()
 {
 	local status=$1
 	[ -e "$tmp_files" ] && rm -f $tmp_files
-	[ -n "$workdir" ] && rm -rf $workdir
+	[ -n "$workdir" ] && rm -rf "$workdir"
 	exit $status
 }
 
@@ -161,12 +146,7 @@ do
 		shift 2 ;;
 	--combine)
 		opt_combine=1
-		if [ "$2" = - ]
-		then
-			first_patch=-
-		else
-			first_patch=$(find_applied_patch "$2") || exit 1
-		fi
+		first_patch=$2
 		shift 2 ;;
 	-R)
 		opt_reverse=1
@@ -217,6 +197,21 @@ do
 	esac
 done
 
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+setup_colors
+
+if [ -n "$first_patch" -a "$first_patch" != - ]
+then
+	first_patch=$(find_applied_patch "$first_patch") || exit 1
+fi
+
 QUILT_DIFF_OPTS="$QUILT_DIFF_OPTS $opt_format"
 
 opt_files=( $(for file in "$@"; do echo "$SUBDIR${file#./}" ; done) )
@@ -260,7 +255,7 @@ then
 	# Add all files in the snapshot into the file list (they may all
 	# have changed).
 	files=( $(find $QUILT_PC/$snap_subdir -type f \
-		  | sed -e "s/^$(quote_bre $QUILT_PC/$snap_subdir/)//" \
+		  | sed -e "s/^$(quote_sed_re $QUILT_PC/$snap_subdir/)//" \
 		  | sort) )
 	printf "%s\n" "${files[@]}" >&4
 	unset files
@@ -328,7 +323,7 @@ IFS=$saved_IFS
 
 if [ -n "$opt_relative" ]
 then
-	workdir=$(gen_tempfile -d $PWD/quilt)
+	workdir=$(gen_tempfile -d "$PWD/quilt")
 	apply_patch_temporarily "$workdir" "$last_patch" "${files[@]}" \
 	|| die 1
 fi
diff --git a/quilt/fold.in b/quilt/fold.in
--- a/quilt/fold.in
+++ b/quilt/fold.in
@@ -6,17 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
 usage()
 {
 	printf $"Usage: quilt fold [-R] [-q] [-f] [-p strip-level]\n"
@@ -83,6 +72,14 @@ then
 	usage
 fi
 
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
 : ${opt_strip_level:=1}
 [ -n "$opt_quiet" ] && patch_args="$patch_args -s"
 [ -z "$opt_force" -o -n "$opt_quiet" ] && patch_args="$patch_args -f"
@@ -92,7 +89,7 @@ top=$(find_top_patch) || exit 1
 
 trap "failed=1" SIGINT
 
-workdir=$(gen_tempfile -d $PWD)
+workdir=$(gen_tempfile -d "$PWD")
 patch -d ${SUBDIR:-.} $QUILT_PATCH_OPTS -p$opt_strip_level \
       --backup --prefix="$workdir/$SUBDIR" $patch_args \
 || failed=1
@@ -105,14 +102,14 @@ if [ -z "$failed" ]
 then
 	# Copy additional files from workdir to the backup directory
 	# For this patch
-	for file in $(find $workdir -type f -a ! -path "$workdir/.timestamp")
+	for file in $(find "$workdir" -type f -a ! -path "$workdir/.timestamp")
 	do
 		file="${file:${#workdir}+1}"
 		backup_file="$(backup_file_name $top "$file")"
 		if ! [ -e "$backup_file" ]
 		then
 			if ! mkdir -p "$(dirname "$backup_file")" ||
-			   ! ln "$workdir/$file" "$backup_file"
+			   ! ln -P "$workdir/$file" "$backup_file"
 			then
 				failed=1
 				break
@@ -123,7 +120,7 @@ fi
 if [ -n "$failed" ]
 then
 	# Restore all files to the state from before applying the patch
-	for file in $(find $workdir -type f -a ! -path "$workdir/.timestamp")
+	for file in $(find "$workdir" -type f -a ! -path "$workdir/.timestamp")
 	do
 		file="${file:${#workdir}+1}"
 		if ! mv -f "$workdir/$file" "$file"
@@ -131,12 +128,12 @@ then
 			printf $"File %s may be corrupted\n" "$file" >&2
 		fi
 	done
-	rm -rf $workdir
+	rm -rf "$workdir"
 	exit 1
 fi
 IFS=$saved_IFS
 
-rm -rf $workdir
+rm -rf "$workdir"
 exit 0
 ### Local Variables:
 ### mode: shell-script
diff --git a/quilt/pop.in b/quilt/pop.in
--- a/quilt/pop.in
+++ b/quilt/pop.in
@@ -6,17 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
 usage()
 {
 	printf $"Usage: quilt pop [-afRqv] [--refresh] [num|patch]\n"
@@ -127,6 +116,7 @@ check_for_pending_changes()
 	then
 		printf $"Patch %s does not remove cleanly (refresh it or enforce with -f)\n" \
 		       "$(print_patch "$patch")" >&2
+		printf $"Hint: \`quilt diff -z' will show the pending changes.\n" >&2
 		status=1
 	fi
 	rm -rf $workdir
@@ -210,6 +200,14 @@ if [ $# -gt 1 -o \( -n "$opt_all" -a $# -ne 0 \) ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 if [ -n "$opt_force" -a -n "$opt_refresh" ]
 then
diff --git a/quilt/refresh.in b/quilt/refresh.in
--- a/quilt/refresh.in
+++ b/quilt/refresh.in
@@ -6,17 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
 usage()
 {
 	printf $"Usage: quilt refresh [-p n|-p ab] [-u|-U num|-c|-C num] [-z[new_name]] [-f] [--no-timestamps] [--no-index] [--diffstat] [--sort] [--backup] [--strip-trailing-whitespace] [patch]\n"
@@ -83,7 +72,7 @@ die()
 	local status=$1
 	[ -n "$tmp_patch" ] && rm -f $tmp_patch
 	[ -n "$tmp_result" ] && rm -f $tmp_result
-	[ -n "$workdir" ] && rm -rf $workdir
+	[ -n "$workdir" ] && rm -rf "$workdir"
 	exit $status
 }
 
@@ -149,6 +138,14 @@ then
 	usage
 fi
 
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
 QUILT_DIFF_OPTS="$QUILT_DIFF_OPTS $opt_format"
 
 patch=$(find_applied_patch "$1") || exit 1
@@ -208,7 +205,7 @@ esac
 trap "die 1" SIGTERM
 
 if [ -n "$opt_fork" ]; then
-	workdir=$(gen_tempfile -d $PWD/quilt)
+	workdir=$(gen_tempfile -d "$PWD/quilt")
 	apply_patch_temporarily "$workdir" "$old_patch" || exit 1
 fi
 
diff --git a/quilt/series.in b/quilt/series.in
--- a/quilt/series.in
+++ b/quilt/series.in
@@ -6,17 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
 usage()
 {
 	printf $"Usage: quilt series [--color[=always|auto|never]] [-v]\n"
@@ -88,6 +77,14 @@ then
 	usage
 fi
 
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
 setup_pager
 
 if [ -n "$opt_verbose$opt_color" ]
@@ -95,10 +92,13 @@ then
 	[ -n "$opt_color" ] && setup_colors
 
 	top=$(top_patch)
-	cat_patches "$color_series_app" \
-		"${opt_verbose:++ }" $(patches_before $top)
-	[ -n "$top" ] && cat_patches "$color_series_top" \
-		"${opt_verbose:+= }" $top
+	if [ -n "$top" ]
+	then
+		cat_patches "$color_series_app" \
+			"${opt_verbose:++ }" $(applied_before $top)
+		cat_patches "$color_series_top" \
+			"${opt_verbose:+= }" $top
+	fi
 	cat_patches "$color_series_una" \
 		"${opt_verbose:+  }" $(patches_after $top)
 else
diff --git a/quilt/setup.in b/quilt/setup.in
--- a/quilt/setup.in
+++ b/quilt/setup.in
@@ -6,24 +6,9 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Version check is irrelevant to this command.
+# Version and series checks are irrelevant to this command.
 skip_version_check=1
-
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-	if [ -n "$SUBDIR" ]
-	then
-		cd $SUBDIR
-		unset SUBDIR
-	fi
-fi
+skip_series_check=1
 
 check_for_existing_directories()
 {
@@ -141,7 +126,7 @@ create_md5sums()
 				;;
 			# In fast mode, we are only interested in patches, so filter out
 			# archives
-			*.tar|*.tar.Z|*.tar.gz|*.tgz|*.tar.bz2|*.tar.xz|*.tar.lz|*.zip|*.7z)
+			*.tar|*.tar.Z|*.tar.gz|*.tgz|*.tar.bz2|*.tar.xz|*.tar.lz|*.tar.zst|*.zip|*.7z)
 				[ -n "$QUILT_SETUP_FAST" ] && continue
 				;;
 		esac
@@ -197,6 +182,12 @@ create_md5sums()
 				set -- $(lzip -cd "$file" | md5sum)
 				echo "$1 $basename"
 				;;
+			"Zstandard compressed data"*)
+				echo -n "z" >&4
+				echo "zstd -cd $file | md5sum" >&5
+				set -- $(zstd -cd "$file" | md5sum)
+				echo "$1 $basename"
+				;;
 		esac
 	done > $output
 	echo >&4
@@ -244,7 +235,7 @@ inspect()
 		ln -s "$targetdir" $tmpdir/build
 		export -f create_md5sums
 	else
-		# Standard mode
+		# Legacy mode
 		mkdir -p $tmpdir/build
 		create_md5sums "$sourcedir" $tmpdir/md5sums
 	fi
@@ -287,15 +278,27 @@ Initializes a source tree from an rpm spec file or a quilt series file.
 --fuzz=N
 	Set the maximum fuzz factor (needs rpm 4.6 or later).
 
---slow	Use the original, slow method to process the spec file. This is the
-	default for now, but that might change in the future. In this mode,
+--slow	Use the original, slow method to process the spec file. In this mode,
 	rpmbuild generates a working tree in a temporary directory while all
 	its actions are recorded, and then everything is replayed from scratch
 	in the target directory.
 
---fast	Use an alternative, faster method to process the spec file. In this
-	mode, rpmbuild is told to generate a working tree directly in the
-	target directory.
+--fast	Use the new, faster method to process the spec file. In this mode,
+	rpmbuild is told to generate a working tree directly in the target
+	directory. This is the default (since quilt version 0.67).
+
+The setup command is only guaranteed to work properly on spec files where
+applying all the patches is the last thing done in the %%prep section. This
+is a design limitation due to the fact that quilt can only operate on
+patches. If other commands in the %%prep section modify the patched files,
+they must come first, otherwise you won't be able to push the patch
+series.
+
+For example, a %%prep section where you first unpack a tarball, then
+apply patches, and lastly perform a tree-wide string substitution, is
+not OK. For \"quilt setup\" to work, it would have to be changed to
+unpacking the tarball, then performing the tree-wide string substitution,
+and lastly applying the patches.
 "
 		exit 0
 	else
@@ -312,6 +315,7 @@ fi
 
 eval set -- "$options"
 
+export QUILT_SETUP_FAST=1
 prefix=
 sourcedir=
 
@@ -337,7 +341,7 @@ do
 		QUILT_SETUP_FAST=
 		shift ;;
 	--fast)
-		export QUILT_SETUP_FAST=1
+		QUILT_SETUP_FAST=1
 		shift ;;
 	--)
 		shift
@@ -348,6 +352,25 @@ done
 if [ $# -ne 1 ]
 then
 	usage
+fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+if [ -n "$SUBDIR" ]
+then
+	# Damn, found an enclosing quilt directory; don't follow its settings
+	cd $SUBDIR
+	unset SUBDIR
+	unset QUILT_PC QUILT_PATCHES QUILT_SERIES
+	: ${QUILT_PC:=.pc}
+	: ${QUILT_PATCHES:=patches}
+	: ${QUILT_SERIES:=series}
 fi
 
 tmpfile=$(gen_tempfile)
diff --git a/quilt/unapplied.in b/quilt/unapplied.in
--- a/quilt/unapplied.in
+++ b/quilt/unapplied.in
@@ -6,17 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
 usage()
 {
 	printf $"Usage: quilt unapplied [patch]\n"
@@ -55,7 +44,17 @@ done
 if [ $# -gt 1 ]
 then
 	usage
-elif [ $# -eq 1 ]
+fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+if [ $# -eq 1 ]
 then
 	start=$(find_patch_in_series "$1") || exit 1
 	patch=$(patch_after "$start")
