feat: update quilt to 0.68-1

diff --git a/quilt/mail.in b/quilt/mail.in
--- a/quilt/mail.in
+++ b/quilt/mail.in
@@ -8,17 +8,6 @@
 
 : ${EDITOR:=vi}
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
 usage()
 {
 	printf $"Usage: quilt mail {--mbox file|--send} [-m text] [-M file] [--prefix prefix] [--sender ...] [--from ...] [--to ...] [--cc ...] [--bcc ...] [--subject ...] [--reply-to message] [--charset ...] [--signature file] [first_patch [last_patch]]\n"
@@ -272,6 +261,14 @@ if [ $# -gt 2 -o \( -z "$opt_send" -a -z "$opt_mbox" \) ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 if [ $# -ge 1 ]
 then
diff --git a/quilt/patches.in b/quilt/patches.in
--- a/quilt/patches.in
+++ b/quilt/patches.in
@@ -6,17 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
 declare -a opt_files=()
 
 usage()
@@ -71,7 +60,7 @@ scan_unapplied()
 	# Quote each file name only once
 	for file in "${opt_files[@]}"
 	do
-		files_bre[${#files_bre[@]}]=$(quote_bre "$file")
+		files_bre[${#files_bre[@]}]=$(quote_grep_re "$file")
 	done
 
 	# "Or" all files in a single pattern
@@ -127,6 +116,15 @@ if [ $# -lt 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
 while [ $# -ge 1 ]
 do
 	opt_files[${#opt_files[@]}]="$SUBDIR$1"
diff --git a/quilt/push.in b/quilt/push.in
--- a/quilt/push.in
+++ b/quilt/push.in
@@ -6,19 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
-setup_colors
-
 usage()
 {
 	printf $"Usage: quilt push [-afqvm] [--fuzz=N] [--merge[=merge|diff3]] [--leave-rejects] [--color[=always|auto|never]] [--refresh] [num|patch]\n"
@@ -138,6 +125,9 @@ apply_patch()
 	elif [ "${patch_file:(-3)}" = ".lz" ]
 	then
 		lzip -cd "$patch_file" | "$@" 2>&1
+	elif [ "${patch_file:(-4)}" = ".zst" ]
+	then
+		zstd -cd "$patch_file" | "$@" 2>&1
 	else
 		"$@" -i "$patch_file" 2>&1
 	fi
@@ -370,6 +360,16 @@ if [ $# -gt 1 -o \( -n "$opt_all" -a $# -ne 0 \) ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+setup_colors
 
 if [ -n "$opt_force" -a -n "$opt_refresh" ]
 then
diff --git a/quilt/revert.in b/quilt/revert.in
--- a/quilt/revert.in
+++ b/quilt/revert.in
@@ -6,17 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
-
 usage()
 {
 	printf $"Usage: quilt revert [-P patch] {file} ...\n"
@@ -65,6 +54,14 @@ then
 	usage
 fi
 
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
 patch=$(find_applied_patch "$opt_patch") || exit 1
 
 status=0
@@ -89,9 +86,9 @@ do
 done
 [ $status -eq 0 ] || exit $status
 
-workdir=$(gen_tempfile -d $PWD)
-add_exit_handler "rm -rf $workdir"
-apply_patch_temporarily $workdir $patch "${@/#/$SUBDIR}" || exit 1
+workdir=$(gen_tempfile -d "$PWD")
+add_exit_handler "rm -rf \"$workdir\""
+apply_patch_temporarily "$workdir" $patch "${@/#/$SUBDIR}" || exit 1
 
 for file in ${*/#/$SUBDIR}
 do
diff --git a/quilt/upgrade.in b/quilt/upgrade.in
--- a/quilt/upgrade.in
+++ b/quilt/upgrade.in
@@ -6,19 +6,9 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Don't abort in version check.
+# Don't abort in version or series check.
 skip_version_check=1
-
-# Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
-then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-fi
+skip_series_check=1
 
 usage()
 {
@@ -62,6 +52,14 @@ then
 	usage
 fi
 
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
 if version_check
 then
 	printf $"The quilt meta-data in %s are already in the version %s format; nothing to do\n" "$QUILT_PC/" "$DB_VERSION"
@@ -76,7 +74,7 @@ printf $"Converting meta-data to version %s\n" "$DB_VERSION"
 
 for patch in $(applied_patches)
 do
-	proper_name="$(grep "^$(quote_bre $patch)"'\(\|\.patch\|\.diff?\)\(\|\.gz\|\.bz2\)\([ \t]\|$\)' $SERIES)"
+	proper_name="$(grep "^$(quote_grep_re $patch)"'\(\|\.patch\|\.diff?\)\(\|\.gz\|\.bz2\)\([ \t]\|$\)' $SERIES)"
 	proper_name=${proper_name#$QUILT_PATCHES/}
 	proper_name=${proper_name%% *}
 	if [ -z "$proper_name" ]
@@ -86,7 +84,7 @@ do
 	fi
 
 	if [ "$patch" != "$proper_name" -a -d $QUILT_PC/$patch ] \
-	   && grep -q "^$(quote_bre $patch)\$" \
+	   && grep -q "^$(quote_grep_re $patch)\$" \
 		   $QUILT_PC/applied-patches
 	then
 		mv $QUILT_PC/$patch $QUILT_PC/$proper_name \
